config/routes.rb
Osizer::Application.routes.draw do
  resources :images

  root 'images#new'

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessor :width, :height
  
  has_attached_file :file, :styles => lambda { |a|
    { :small => "#{a.instance.width}x#{a.instance.height}#" }
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create

    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params[:image].permit(:width, :height, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.slim
= form_for @image do |form|
  - if @image.errors.any?
    #error_explanation
      h2 = "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      ul
        - @image.errors.full_messages.each do |message|
          li = message

  label Image
  = form.file_field :file
  br
  label Crop Width
  = form.text_field :width
  br
  label Crop Height
  = form.text_field :height
  br
  label Ratio Crop
  input type="radio" name="cropOption" value="Ratio Crop"
  br
  label No Scale
  input type="radio" name="cropOption" value="No scale"
  br
  = form.submit 'Submit'

app/views/images/edit.html.slim
h1 Editing image

== render 'form'

= link_to 'Show', @image
'|
= link_to 'Back', images_path

app/views/images/index.html.slim
h1 Listing images

table
  tr
    th Image
    th
    th
    th

  - @images.each do |image|
    tr
      td = image_tag image.file.url(:small)
      td = link_to 'Show', image
      td = link_to 'Edit', edit_image_path(image)
      td = link_to 'Destroy', image, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Image', new_image_path

app/views/images/new.html.slim
h1 New image

== render 'form'

= link_to 'Back', images_path

app/views/images/show.html.slim
p#notice = notice

h4 Original
= image_tag @image.file.url(:original)

h4 Small
= image_tag @image.file.url(:small)

= link_to 'Edit', edit_image_path(@image)
'|
= link_to 'Back', images_path

app/views/layouts/application.slim
doctype html
html
  head
  title Osizer
  = stylesheet_link_tag    "application", media: "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
body
  
  #wrapper
    = yield

  
  
	